/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sustainability;

import java.util.ArrayList;

/**
 *
 * @HARRY
 */
public class SustainabilityGUI extends javax.swing.JFrame {
    //declaring and creating the array lists
    private ArrayList <AquaticLife> aquaticList;
    private ArrayList <Pollution> pollutionList;
    private Questionnaire questionnaire;

    /**
     * Creates new form Link2
     */
    public SustainabilityGUI() {
        initComponents();
        initPollutionInfo();
        initAquaticInfo();
        initQuestionnaire();
    }

    //arraylist for the pollution info
    private void initPollutionInfo() {
        pollutionList = new ArrayList<>();
        pollutionList.add(new Pollution("Plastic", "Animals can ingest items", "Reduce your plastic usage"));
        pollutionList.add(new Pollution("Industrial", "Can poison & contaminate water", "Advocate against the dumping of waste runoff entering the oceans"));
        pollutionList.add(new Pollution("Light", "Disrupt & Expose creatures as prey", "Minimize marine lighting, floodlights or " + "\n" + "Spotlights within 5km of an offshore island."));
        
    } 
    
    //arraylist for the aquatic info
    private void initAquaticInfo() {
        aquaticList = new ArrayList<>();
        aquaticList.add(new AquaticLife("Blue Whale", "North Atlantic", 20000, "Endangered"));
        aquaticList.add(new AquaticLife("Hawksbill Sea Turtle", "Tropical Waters", 8000, "Critically Endangered"));
        aquaticList.add(new AquaticLife("Great White Shark", "Coastal Shores Worldwide", 3500, "Vulnerable"));
    }
    
    private void initQuestionnaire() {
        questionnaire = new Questionnaire(
        "Do you know what is the leading cause of pollution in our ocean?",
        new String[]{"Plastic Waste", "Industrial Runoff", "Oil Spills", "Overfishing"},
        "Plastic Waste"
        );

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPNL = new javax.swing.JPanel();
        exitBTN = new javax.swing.JButton();
        titleLBL = new javax.swing.JLabel();
        text1LBL = new javax.swing.JLabel();
        text2LBL = new javax.swing.JLabel();
        label1LBL = new javax.swing.JLabel();
        label2LBL = new javax.swing.JLabel();
        iconLBL = new javax.swing.JLabel();
        icon2LBL = new javax.swing.JLabel();
        answerTF = new javax.swing.JTextField();
        animalBTN = new javax.swing.JButton();
        pollutionBTN = new javax.swing.JButton();
        checkBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaTA = new javax.swing.JTextArea();
        answer1LBL = new javax.swing.JLabel();
        answer2LBL = new javax.swing.JLabel();
        answer3LBL = new javax.swing.JLabel();
        answer4LBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ocean Cleanup Info | Harry");
        setResizable(false);

        backgroundPNL.setBackground(new java.awt.Color(0, 124, 186));
        backgroundPNL.setPreferredSize(new java.awt.Dimension(650, 450));

        exitBTN.setBackground(new java.awt.Color(210, 231, 241));
        exitBTN.setForeground(new java.awt.Color(148, 196, 228));
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(210, 231, 241));
        titleLBL.setText("Ocean Cleanup Info");

        text1LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text1LBL.setForeground(new java.awt.Color(210, 231, 241));
        text1LBL.setText("My Goal Here is to provide a some brief information about");

        text2LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text2LBL.setForeground(new java.awt.Color(210, 231, 241));
        text2LBL.setText("Global warming and its impact on our Oceans");

        label1LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1LBL.setForeground(new java.awt.Color(210, 231, 241));
        label1LBL.setText("Do you know what is the leading");

        label2LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label2LBL.setForeground(new java.awt.Color(210, 231, 241));
        label2LBL.setText("Cause of pollution in our ocean is");

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sustainability/Wave.png"))); // NOI18N

        icon2LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sustainability/sdg14.png"))); // NOI18N

        animalBTN.setBackground(new java.awt.Color(210, 231, 241));
        animalBTN.setForeground(new java.awt.Color(148, 196, 228));
        animalBTN.setText("Aquatic Life Info");
        animalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalBTNActionPerformed(evt);
            }
        });

        pollutionBTN.setBackground(new java.awt.Color(210, 231, 241));
        pollutionBTN.setForeground(new java.awt.Color(148, 196, 228));
        pollutionBTN.setText("Pollution Information");
        pollutionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollutionBTNActionPerformed(evt);
            }
        });

        checkBTN.setBackground(new java.awt.Color(210, 231, 241));
        checkBTN.setForeground(new java.awt.Color(148, 196, 228));
        checkBTN.setText("Check");
        checkBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBTNActionPerformed(evt);
            }
        });

        textareaTA.setColumns(20);
        textareaTA.setRows(5);
        jScrollPane2.setViewportView(textareaTA);

        answer1LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        answer1LBL.setForeground(new java.awt.Color(210, 231, 241));
        answer1LBL.setText("Plastic Waste");

        answer2LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        answer2LBL.setForeground(new java.awt.Color(210, 231, 241));
        answer2LBL.setText("Industrial Runoff");

        answer3LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        answer3LBL.setForeground(new java.awt.Color(210, 231, 241));
        answer3LBL.setText("Oil Spills");

        answer4LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        answer4LBL.setForeground(new java.awt.Color(210, 231, 241));
        answer4LBL.setText("Overfishing");

        javax.swing.GroupLayout backgroundPNLLayout = new javax.swing.GroupLayout(backgroundPNL);
        backgroundPNL.setLayout(backgroundPNLLayout);
        backgroundPNLLayout.setHorizontalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icon2LBL)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text1LBL)
                            .addGroup(backgroundPNLLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(titleLBL))))
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(exitBTN))
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text2LBL)
                            .addGroup(backgroundPNLLayout.createSequentialGroup()
                                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(animalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pollutionBTN))
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(iconLBL)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(answer1LBL))
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(answer2LBL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label1LBL)
                        .addGroup(backgroundPNLLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPNLLayout.createSequentialGroup()
                                    .addComponent(checkBTN)
                                    .addGap(269, 269, 269))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPNLLayout.createSequentialGroup()
                                    .addComponent(answerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(230, 230, 230)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPNLLayout.createSequentialGroup()
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundPNLLayout.createSequentialGroup()
                                .addComponent(label2LBL)
                                .addGap(59, 59, 59)
                                .addComponent(answer4LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(answer3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );
        backgroundPNLLayout.setVerticalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addComponent(titleLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icon2LBL))
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answer1LBL)
                            .addComponent(answer3LBL))
                        .addGap(130, 130, 130)
                        .addComponent(pollutionBTN)
                        .addGap(26, 26, 26)
                        .addComponent(animalBTN))
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text2LBL)
                        .addGap(66, 66, 66)
                        .addComponent(label1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer4LBL)
                            .addComponent(answer2LBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(answerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBTN)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconLBL))
                        .addGap(18, 18, 18)
                        .addComponent(exitBTN)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pollutionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollutionBTNActionPerformed
        // TODO add your handling code here:
        textareaTA.setText(""); // Clear text area
        for (Pollution pollution : pollutionList) {
            textareaTA.append(pollution.toString() + "\n\n");
        }
    }//GEN-LAST:event_pollutionBTNActionPerformed

    private void animalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalBTNActionPerformed
        // TODO add your handling code here:
        textareaTA.setText(""); // Clear text area
        for (AquaticLife species : aquaticList) {
            textareaTA.append(species.toString() + "\n");
        }
    }//GEN-LAST:event_animalBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void checkBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBTNActionPerformed
        // TODO add your handling code here:
        String userAnswer = answerTF.getText();
        
        if (questionnaire.checkAnswer(userAnswer)) {
            textareaTA.setText("Yes! Plastic Waste is the Leading cause of pollution" + "\n" + "In our oceans");
        }else {
            textareaTA.setText("Unfortunately no, but you can try again");
        }
    }//GEN-LAST:event_checkBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SustainabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SustainabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SustainabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SustainabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SustainabilityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton animalBTN;
    private javax.swing.JLabel answer1LBL;
    private javax.swing.JLabel answer2LBL;
    private javax.swing.JLabel answer3LBL;
    private javax.swing.JLabel answer4LBL;
    private javax.swing.JTextField answerTF;
    private javax.swing.JPanel backgroundPNL;
    private javax.swing.JButton checkBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel icon2LBL;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1LBL;
    private javax.swing.JLabel label2LBL;
    private javax.swing.JButton pollutionBTN;
    private javax.swing.JLabel text1LBL;
    private javax.swing.JLabel text2LBL;
    private javax.swing.JTextArea textareaTA;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
